version: '3.7' # https://docs.docker.com/compose/compose-file/compose-versioning/

services:

  # Initialize the DB container:
  #   envdir .env.priv docker-compose up db
  #
  # Destroy all services and their related storage:
  #   envdir .env.priv docker-compose down --volumes
  db:
    image: postgres:12.9-alpine
    ports:
      - '127.10.0.1:5432:5432' # 127.10.0.1      pg.zero2prod.test
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:?mandatory}
      POSTGRES_DB: newsletter