version: '3.7' # https://docs.docker.com/compose/compose-file/compose-versioning/

services:

  # Test with:
  #   ./manage/with_env docker-compose up prod-test
  #   http 127.10.0.2:8080/health
  prod-test:
    image: local/zero2prod
    environment:
      PGUSER: ${PGUSER:?mandatory}
      PGPASSWORD: ${PGPASSWORD:?mandatory}
      PGHOST: "db"
      PGDATABASE: ${PGDATABASE:?mandatory}
      BIND: 0.0.0.0:8080
    ports:
      - '127.10.0.2:8080:8080'
    depends_on:
      - db

  # Initialize the DB container:
  #   ./manage/with_env docker-compose up db
  #
  # Destroy all services and their related storage:
  #   ./manage/with_env docker-compose down --volumes
  db:
    image: postgres:12.9-alpine
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - '127.10.0.1:5432:5432' # 127.10.0.1      pg.zero2prod.test
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD:?mandatory}
      POSTGRES_DB: newsletter