CREATE TABLE subscriptions
(
    id    INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE CHECK (email <> ''),
    name VARCHAR(255) NOT NULL CHECK (name <> ''),
    subscribed_at TIMESTAMPTZ NOT NULL
)