CREATE TYPE QUEUE_STATUS AS ENUM ('Queued', 'Running', 'Failed');

CREATE TABLE queue
    ( id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
    , status QUEUE_STATUS NOT NULL DEFAULT 'Queued'
    , message JSONB NOT NULL
    );
