#!/bin/bash

set -e

if ! [ -x "$(command -v "$1")" ]; then
  echo "'$1' is not a program!"
  exit 1
fi

set -a
source .env.priv
source .env.pub
set +a

# Required by sqlx
export DATABASE_URL="postgres://${PGUSER}:${PGPASSWORD}@${PGHOST}:5432/${PGDATABASE}"

exec "$@"